<?php

/**
 * @file
 * Provides indexing on entity revisions.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\search_api_revisions\Hooks\SearchApiRevisionsHooks;

/**
 * Implements hook_entity_insert().
 */
function search_api_revisions_entity_insert(EntityInterface $entity): void {
  \Drupal::classResolver(SearchApiRevisionsHooks::class)->entityInsert($entity);
}

/**
 * Implements hook_entity_update().
 */
function search_api_revisions_entity_update(EntityInterface $entity): void {
  \Drupal::classResolver(SearchApiRevisionsHooks::class)->entityUpdate($entity);
}

/**
 * Implements hook_entity_predelete().
 */
function search_api_revisions_entity_predelete(EntityInterface $entity): void {
  \Drupal::classResolver(SearchApiRevisionsHooks::class)->entityPreDelete($entity);
}

/**
 * Implements hook_entity_revision_delete().
 */
function search_api_revisions_entity_revision_delete(EntityInterface $entity): void {
  \Drupal::classResolver(SearchApiRevisionsHooks::class)->entityRevisionDelete($entity);
}
